-- Crear un nuevo usuario (esquema)
CREATE USER TVA_CAR IDENTIFIED BY TVA_CAR_PASSWORD;
GRANT CONNECT, RESOURCE TO TVA_CAR;

-- Conectar como el nuevo usuario
ALTER SESSION SET CURRENT_SCHEMA = TVA_CAR;

-- Crear la tabla CLIENTE
CREATE TABLE CLIENTE (
    CLIENTE_ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(500 BYTE),
    CLAVE VARCHAR2(10 BYTE),
    MAIL VARCHAR2(1000 BYTE),
    ESTATUS VARCHAR2(1000 BYTE)
);

-- Crear la tabla PRODUCTO
CREATE TABLE PRODUCTO (
    PRODUCTO_ID NUMBER PRIMARY KEY,
    DESCRIPCION VARCHAR2(500 BYTE),
    COSTO_UNITARIO NUMBER,
    ESTATUS VARCHAR2(1000 BYTE)
);

-- Crear la tabla VENTA
CREATE TABLE VENTA (
    VENTA_ID NUMBER PRIMARY KEY,
    FECHA DATE,
    CLIENTE_ID NUMBER,
    ESTATUS VARCHAR2(100 BYTE),
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID)
);

-- Crear la tabla DETALLE_VENTA
CREATE TABLE DETALLE_VENTA (
    VENTA_ID NUMBER,
    PRODUCTO_ID NUMBER,
    CANTIDAD NUMBER,
    DESCUENTO NUMBER,
    TOTAL NUMBER,
    PRIMARY KEY (VENTA_ID, PRODUCTO_ID),
    FOREIGN KEY (VENTA_ID) REFERENCES VENTA(VENTA_ID),
    FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTO(PRODUCTO_ID)
);
